"""added create datetime in database

Revision ID: 00bf0b58d49d
Revises: fdbd618928db
Create Date: 2026-02-16 19:51:45.862177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bf0b58d49d'
down_revision: Union[str, Sequence[str], None] = 'fdbd618928db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_datetime')
    # ### end Alembic commands ###
