"""Add phone column to orders table

Revision ID: 40f18554bb8a
Revises: 00bf0b58d49d
Create Date: 2026-03-16 16:23:53.238901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f18554bb8a'
down_revision: Union[str, Sequence[str], None] = '00bf0b58d49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
